#Integracion Continua para un proyecto Django
name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configurar base de datos (SQLite para test)
      run: |
        python manage.py migrate --settings=mi_proyecto.settings

    - name: Ejecutar pruebas
      run: |
        python manage.py test --settings=mi_proyecto.settings
