name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/testCI" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"   # cambia si usas otra versión

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Migraciones (SQLite para test)
      run: python manage.py migrate

    - name: Ejecutar pruebas
      run: python manage.py test
